### ISSUE TITLE
批量导入导出的功能

### ISSUE THREAD

**Issue by nantongxue** [202252197/ChatGPT_JCM#6]
现有的程序基本上都是“一问一答”形式的，一次输入一个问题（提示词），然后生成一个答案。
希望有可以一次输入（或以表格形式导入）多个问题（提示词），然后批量生成对应问题（提示词）的答案，最后将生成的结果批量导出的功能，对实际运营（不是日常玩玩）会非常有用
参考https://batchgpt.com/

**Comment by 202252197** [comment]
好的会支持的@
