### ISSUE TITLE
聊天中断：输出内容变成只有一个表情包了

### ISSUE THREAD

**Issue by ZS629** [202252197/ChatGPT_JCM#60]
可能是会话太长了吗，突然变成表情包了
![image](https://user-images.githubusercontent.com/127756463/229056852-f76ef440-7bff-4e1d-a39c-705ffae5f69f.png)

**Comment by minlo-18** [comment]
我这一打开他就只会输出emoji，真特么烦啊😀😀😀😀😀😀

**Comment by ZS629** [comment]
看来你需要一个强大的代理服务器😃

**Comment by minlo-18** [comment]
> 看来你需要一个强大的代理服务器😃

彳亍😃
