### ISSUE TITLE
啊？为啥我输入啥都只回一个😀，作者大大麻烦看看啊

### ISSUE THREAD

**Issue by minlo-18** [202252197/ChatGPT_JCM#64]
![image](https://user-images.githubusercontent.com/60054647/229265457-96cd73e6-e34d-43d0-a98e-6cee781b1c0c.png)

**Comment by ZS629** [comment]
你需要魔法😃

**Comment by minlo-18** [comment]
> 你需要魔法😃

😃哥们我这梯子全局的 gpt正常使用😃

**Comment by woxiaohai** [comment]
我用魔法怎么也不行
